- README.md
Addresses #7 
Added a `README.md` file to the repository.
The file consists of the Introduction, as well as License. I'll edit it if something else is needed.
> Create README.md - #7

- README.md
> Add README.md - Closes #7

- downloaded/setup_postgresql.Linux
I changed the the script to install Postgres 9.6 instead of 10.
Closes #12
> Force script to install postgres 9.6 - Closes #12

- packaged/lisk.sh
> Switched the parsing of config.json to jq - Closes #18

- packaged/etc/snapshot.json
> Update snapshot configuration file to match with 1.0.0 specification - Closes #26

- downloaded/installLisk.sh
Remove ntp check, logrotate config creation and all instances of sudo
> Remove sudo from installLisk.sh - Closes #54

- packaged/lisk_bridge.sh
Config migration is now out of scope
> Remove config migration lisk bridge - Closes #51

- downloaded/lisk_bridge.sh
Fix how local_tar argument is handled - Closes #71
> Fix local tar argument passing in lisk_bridge.sh

- downloaded/installLisk.sh
> Update the config file path and check for master password - Closes #66

- downloaded/lisk_bridge.sh
> Fix lisk_bridge to overwrite downloaded file - Closes #89

- downloaded/lisk_bridge.sh
> Add rm -rf back into lisk_bridge.sh

- downloaded/lisk_bridge.sh
> Update "see migration guide" text to have link to migration guide

- downloaded/lisk_bridge.sh
> Lisk Bridge script is not compatible with 1.x.x release - Closes #112

- downloaded/lisk_bridge.sh
> Add some sanity checks to lisk_bridge.sh - Closes #126

- downloaded/lisk_bridge.sh
0.3.0 version of #127 - closes #126
> Add some sanity checks to lisk_bridge.sh

- downloaded/installLisk.sh
> Fix jq path

- downloaded/installLisk.sh
> Fix indents

- downloaded/installLisk.sh
Accepted PRs #135 and #136 (thanks @nekonenene)
Just need to sign the commits
> Sign-off PRs #135 and #136

- downloaded/installLisk.sh
> Signoffs for 0.3.0

- packaged/lisk.sh
- packaged/lisk_snapshot.sh
- packaged/shared.sh
Moved get_config from lisk.sh to shared.sh so that lisk_snapshot.sh can use it
Closes #148
> Update lisk_snapshot.sh for 1.1 - Closes #148

- downloaded/installLisk.sh
- packaged/shared.sh
> Swap env.sh and shared.sh - Closes #150

- downloaded/installLisk.sh
> Update installLisk.sh to not use 'latest' build

- downloaded/installLisk.sh
- downloaded/lisk_bridge.sh
Update lisk_bridge.sh api url for 1.0
Get correct field from config
Get correct field from json
Closes #172
> Update lisk_bridge.sh api url for 1.0 - Closes #172

- downloaded/installLisk.sh
> Moved latest.txt check after local build check - Closes #174

- downloaded/installLisk.sh
When installing, check if Postgresql is running and if it is, bail out with an error
Closes #187
> Postgres running check - Closes #187

- packaged/lisk.sh
Suppress parse error when pm2 is not running and check_status function gets called
Closes #186
> Suppress lisk.sh parse error - Closes #186

- downloaded/installLisk.sh
Change LISK_NETWORK to match specified network on install/upgrade
Closes #191
> Set LISK_NETWORK on install/upgrade - Closes #191
